// src/lib/mockData.ts
import type { Product } from '@/types/product';

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "REM-001",
        name: "Remera Lisa Premium Algodón",
        category: "Remeras",
        quality: "PREMIUM",
        description: "Algodón peinado premium, corte oversize ideal para estampar.",
        basePrice: 15000,
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 2450,
        sizes: "XS-7XL",
        colors: 8
    },
    {
        id: "REM-002",
        name: "Remera Básica Cuello V",
        category: "Remeras",
        quality: "BASIC",
        description: "Clásica remera cuello V de uso diario.",
        basePrice: 9500,
        image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 5000,
        sizes: "S-XXL",
        colors: 5
    },
    {
        id: "REM-003",
        name: "Remera Boxy Fit Heavy",
        category: "Remeras",
        quality: "NUEVO",
        description: "Corte cuadrado y tejido extra pesado 240g.",
        basePrice: 19000,
        image: "invalid-url-to-force-error.jpg",
        stockStatus: "LOW",
        totalStock: 50,
        sizes: "M-XL",
        colors: 3
    },
    {
        id: "REM-004",
        name: "Remera Deportiva Dry Fit",
        category: "Remeras",
        quality: "STANDARD",
        description: "Tecnología de secado rápido anti transpiración.",
        basePrice: 12000,
        image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1200,
        sizes: "XS-3XL",
        colors: 6
    },
    {
        id: "REM-005",
        name: "Remera Pima Heavyweight",
        category: "Remeras",
        quality: "STANDARD",
        description: "Algodón Pima peruano, máxima suavidad y durabilidad.",
        basePrice: 18900,
        image: "https://images.unsplash.com/photo-1583332462215-dcfaaf5625e1?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1540,
        sizes: "XS-5XL",
        colors: 12
    },
    {
        id: "REM-006",
        name: "Remera Cuello Redondo 24/1",
        category: "Remeras",
        quality: "BASIC",
        description: "Algodón 24/1 clásico, ideal para sublimación y transfer.",
        basePrice: 8500,
        image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 8200,
        sizes: "S-XXL",
        colors: 15
    },
    {
        id: "REM-007",
        name: "Remera Manga Larga Básica",
        category: "Remeras",
        quality: "STANDARD",
        description: "Manga larga recta, ideal para uniformes corporativos.",
        basePrice: 13500,
        image: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1800,
        sizes: "S-3XL",
        colors: 7
    },
    {
        id: "REM-008",
        name: "Remera Oversize Drop Shoulder",
        category: "Remeras",
        quality: "PREMIUM",
        description: "Hombro caído, corte ultra relajado streetwear.",
        basePrice: 17500,
        image: "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 900,
        sizes: "S-XXL",
        colors: 6
    },
    {
        id: "REM-009",
        name: "Remera Ringer Retro",
        category: "Remeras",
        quality: "STANDARD",
        description: "Estilo retro con cuello y puños contrastantes.",
        basePrice: 11000,
        image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 280,
        sizes: "S-XL",
        colors: 4
    },
    {
        id: "REM-010",
        name: "Remera Muscle Fit",
        category: "Remeras",
        quality: "STANDARD",
        description: "Corte entallado para silueta atlética.",
        basePrice: 10500,
        image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 2100,
        sizes: "S-XXL",
        colors: 8
    },
    {
        id: "REM-011",
        name: "Remera Polo Piqué",
        category: "Remeras",
        quality: "PREMIUM",
        description: "Polo clásico en piqué de algodón, cuello y puños acanalados.",
        basePrice: 16500,
        image: "https://images.unsplash.com/photo-1625910513413-5fc66e54f1b5?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1650,
        sizes: "S-3XL",
        colors: 10
    },
    {
        id: "REM-012",
        name: "Remera Henley Botones",
        category: "Remeras",
        quality: "STANDARD",
        description: "Cuello henley con 3 botones de madera.",
        basePrice: 12500,
        image: "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 420,
        sizes: "S-XXL",
        colors: 5
    },
    {
        id: "REM-013",
        name: "Remera Tie Dye Artesanal",
        category: "Remeras",
        quality: "NUEVO",
        description: "Teñido artesanal a mano, cada prenda es única.",
        basePrice: 21000,
        image: "https://images.unsplash.com/photo-1601379329542-31a627e93a04?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 150,
        sizes: "S-XL",
        colors: 6
    },
    {
        id: "REM-014",
        name: "Remera Crop Top Mujer",
        category: "Remeras",
        quality: "STANDARD",
        description: "Corte cropped femenino, algodón suave 160g.",
        basePrice: 9800,
        image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 3200,
        sizes: "XS-XL",
        colors: 9
    },
    {
        id: "REM-015",
        name: "Remera Raglan Baseball",
        category: "Remeras",
        quality: "BASIC",
        description: "Manga raglan bicolor estilo baseball americano.",
        basePrice: 11500,
        image: "https://images.unsplash.com/photo-1618517351616-38fb9c5210c6?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1900,
        sizes: "S-XXL",
        colors: 7
    },
    {
        id: "REM-016",
        name: "Remera Tank Top Gym",
        category: "Remeras",
        quality: "STANDARD",
        description: "Musculosa deportiva de secado rápido.",
        basePrice: 8000,
        image: "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 4500,
        sizes: "S-XXL",
        colors: 6
    },
    {
        id: "REM-017",
        name: "Remera Lino Premium",
        category: "Remeras",
        quality: "PREMIUM",
        description: "Mezcla algodón-lino para verano, textura natural.",
        basePrice: 22000,
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 380,
        sizes: "S-XL",
        colors: 4
    },
    {
        id: "REM-018",
        name: "Remera Térmica Primera Piel",
        category: "Remeras",
        quality: "STANDARD",
        description: "Interior térmico de microfibra para invierno.",
        basePrice: 14000,
        image: "https://images.unsplash.com/photo-1564557287817-3085a4d5fb60?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 2800,
        sizes: "S-3XL",
        colors: 3
    },
    {
        id: "REM-019",
        name: "Remera Acid Wash Vintage",
        category: "Remeras",
        quality: "NUEVO",
        description: "Lavado ácido artesanal, look vintage gastado.",
        basePrice: 19500,
        image: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 200,
        sizes: "S-XL",
        colors: 3
    },
    {
        id: "REM-020",
        name: "Remera Cuello Alto Mock Neck",
        category: "Remeras",
        quality: "PREMIUM",
        description: "Cuello alto tipo mock, algodón compacto premium.",
        basePrice: 16000,
        image: "https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 750,
        sizes: "S-XXL",
        colors: 5
    },
    // --- BUZOS ---
    {
        id: "BUZ-001",
        name: "Buzo Hoodie Oversized",
        category: "Buzos",
        quality: "BASIC",
        description: "Frisa invisible pesada, cordón al tono.",
        basePrice: 28500,
        image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 12,
        sizes: "S-4XL",
        colors: 4
    },
    {
        id: "BUZ-002",
        name: "Buzo Canguro Clásico",
        category: "Buzos",
        quality: "STANDARD",
        description: "Hoodie canguro con bolsillo frontal y capucha forrada.",
        basePrice: 25000,
        image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1850,
        sizes: "S-3XL",
        colors: 8
    },
    {
        id: "BUZ-003",
        name: "Buzo Crewneck Sin Capucha",
        category: "Buzos",
        quality: "PREMIUM",
        description: "Cuello redondo limpio, frisa premium 320g.",
        basePrice: 27000,
        image: "https://images.unsplash.com/photo-1614975059251-992f11792571?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1200,
        sizes: "S-XXL",
        colors: 10
    },
    {
        id: "BUZ-004",
        name: "Buzo Zip-Up Campera",
        category: "Buzos",
        quality: "STANDARD",
        description: "Cierre full frontal con capucha, ideal para personalizar.",
        basePrice: 31000,
        image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 900,
        sizes: "S-3XL",
        colors: 6
    },
    {
        id: "BUZ-005",
        name: "Buzo Oversize Boxy Heavy",
        category: "Buzos",
        quality: "PREMIUM",
        description: "Corte cuadrado ultra pesado 380g, drop shoulder.",
        basePrice: 35000,
        image: "https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 300,
        sizes: "S-XL",
        colors: 4
    },
    {
        id: "BUZ-006",
        name: "Buzo Hoodie Tie Dye",
        category: "Buzos",
        quality: "NUEVO",
        description: "Hoodie teñido artesanal, frisa pesada.",
        basePrice: 33000,
        image: "https://images.unsplash.com/photo-1542327897-d73f4005b533?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 120,
        sizes: "S-XL",
        colors: 5
    },
    {
        id: "BUZ-007",
        name: "Buzo Polar Microfibra",
        category: "Buzos",
        quality: "BASIC",
        description: "Polar ultra liviano y abrigado, anti-pilling.",
        basePrice: 22000,
        image: "https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 3500,
        sizes: "S-3XL",
        colors: 7
    },
    {
        id: "BUZ-008",
        name: "Buzo Mock Neck Cuello Alto",
        category: "Buzos",
        quality: "PREMIUM",
        description: "Cuello alto estilo mock, minimalista urbano.",
        basePrice: 29000,
        image: "https://images.unsplash.com/photo-1611312449412-6cefac5dc3e4?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 680,
        sizes: "S-XXL",
        colors: 5
    },
    // --- PANTALONES ---
    {
        id: "PAN-001",
        name: "Jogger Cotton Rústico",
        category: "Pantalones",
        quality: "NUEVO",
        description: "Algodón rústico liviano, puños ajustables.",
        basePrice: 22000,
        image: "https://images.unsplash.com/photo-1510832842233-436cb8794406?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 300,
        sizes: "XS-XXL",
        colors: 3
    },
    {
        id: "PAN-002",
        name: "Jogger Frisa Pesada",
        category: "Pantalones",
        quality: "STANDARD",
        description: "Frisa invisible 300g con bolsillos laterales.",
        basePrice: 24000,
        image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 2200,
        sizes: "S-3XL",
        colors: 6
    },
    {
        id: "PAN-003",
        name: "Pantalón Cargo Wide Leg",
        category: "Pantalones",
        quality: "NUEVO",
        description: "Corte wide leg con bolsillos cargo, tendencia urbana.",
        basePrice: 26000,
        image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 400,
        sizes: "S-XL",
        colors: 4
    },
    {
        id: "PAN-004",
        name: "Pantalón Deportivo Dry Fit",
        category: "Pantalones",
        quality: "STANDARD",
        description: "Secado rápido, corte recto para entrenamiento.",
        basePrice: 18000,
        image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 3100,
        sizes: "S-XXL",
        colors: 5
    },
    {
        id: "PAN-005",
        name: "Bermuda Jogger Corta",
        category: "Pantalones",
        quality: "BASIC",
        description: "Bermuda de algodón con elástico y cordón.",
        basePrice: 14000,
        image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 4200,
        sizes: "S-XXL",
        colors: 8
    },
    {
        id: "PAN-006",
        name: "Short Deportivo Mesh",
        category: "Pantalones",
        quality: "STANDARD",
        description: "Mesh deportivo con calza interior integrada.",
        basePrice: 12000,
        image: "https://images.unsplash.com/photo-1562886877-b85cf9162d40?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 2800,
        sizes: "S-XXL",
        colors: 6
    },
    {
        id: "PAN-007",
        name: "Pantalón Chino Algodón",
        category: "Pantalones",
        quality: "PREMIUM",
        description: "Chino de algodón premium, corte slim para uniformes.",
        basePrice: 28000,
        image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 900,
        sizes: "28-42",
        colors: 5
    },
    // --- CAMPERAS ---
    {
        id: "CAM-001",
        name: "Campera Rompevientos Liviana",
        category: "Camperas",
        quality: "STANDARD",
        description: "Nylon ripstop ultra liviano, repelente al agua.",
        basePrice: 32000,
        image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 750,
        sizes: "S-3XL",
        colors: 6
    },
    {
        id: "CAM-002",
        name: "Campera Puffer Inflable",
        category: "Camperas",
        quality: "PREMIUM",
        description: "Relleno sintético aislante, ultraliviana y comprimible.",
        basePrice: 45000,
        image: "https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 180,
        sizes: "S-XXL",
        colors: 5
    },
    {
        id: "CAM-003",
        name: "Campera Coach Jacket",
        category: "Camperas",
        quality: "STANDARD",
        description: "Estilo coach con botones a presión, ideal para estampar.",
        basePrice: 28000,
        image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 600,
        sizes: "S-XXL",
        colors: 4
    },
    {
        id: "CAM-004",
        name: "Campera Bomber Satinada",
        category: "Camperas",
        quality: "PREMIUM",
        description: "Bomber clásica en tela satinada con forro interior.",
        basePrice: 42000,
        image: "https://images.unsplash.com/photo-1557418669-b282536fad08?w=500&q=80",
        stockStatus: "LOW",
        totalStock: 250,
        sizes: "S-XL",
        colors: 3
    },
    {
        id: "CAM-005",
        name: "Campera Softshell Térmica",
        category: "Camperas",
        quality: "STANDARD",
        description: "Softshell con membrana térmica y resistente al viento.",
        basePrice: 38000,
        image: "https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 520,
        sizes: "S-3XL",
        colors: 4
    },
    // --- CONJUNTOS ---
    {
        id: "CON-001",
        name: "Conjunto Deportivo Completo",
        category: "Conjuntos",
        quality: "STANDARD",
        description: "Buzo + jogger combinados, ideal para equipos.",
        basePrice: 42000,
        image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 800,
        sizes: "S-3XL",
        colors: 6
    },
    {
        id: "CON-002",
        name: "Conjunto Jogging Frisa",
        category: "Conjuntos",
        quality: "BASIC",
        description: "Hoodie + pantalón frisa, combo invierno.",
        basePrice: 48000,
        image: "https://images.unsplash.com/photo-1483118714900-540cf339fd46?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 650,
        sizes: "S-XXL",
        colors: 5
    },
    {
        id: "CON-003",
        name: "Conjunto Dry Fit Running",
        category: "Conjuntos",
        quality: "PREMIUM",
        description: "Remera + short deportivo, tecnología de alto rendimiento.",
        basePrice: 35000,
        image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1100,
        sizes: "S-XXL",
        colors: 7
    },
    // --- ACCESORIOS ---
    {
        id: "ACC-001",
        name: "Gorra Dad Hat Algodón",
        category: "Accesorios",
        quality: "BASIC",
        description: "Gorra desestructurada con hebilla metálica trasera.",
        basePrice: 7500,
        image: "https://images.unsplash.com/photo-1588850561407-ed78c334e67a?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 5600,
        sizes: "Único",
        colors: 12
    },
    {
        id: "ACC-002",
        name: "Gorra Trucker Malla",
        category: "Accesorios",
        quality: "STANDARD",
        description: "Frente estructurado con malla trasera transpirable.",
        basePrice: 8500,
        image: "https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 4200,
        sizes: "Único",
        colors: 10
    },
    {
        id: "ACC-003",
        name: "Gorra Snapback Premium",
        category: "Accesorios",
        quality: "PREMIUM",
        description: "Visera plana, cierre snapback, ideal para bordar.",
        basePrice: 9500,
        image: "https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 3000,
        sizes: "Único",
        colors: 8
    },
    {
        id: "ACC-004",
        name: "Beanie Lana Tejida",
        category: "Accesorios",
        quality: "STANDARD",
        description: "Gorro tipo beanie en lana acrílica, doble pliegue.",
        basePrice: 6500,
        image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 3800,
        sizes: "Único",
        colors: 9
    },
    {
        id: "ACC-005",
        name: "Tote Bag Algodón Crudo",
        category: "Accesorios",
        quality: "BASIC",
        description: "Bolsa tote de algodón sin blanquear, lienzo grueso.",
        basePrice: 5000,
        image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 7000,
        sizes: "Único",
        colors: 3
    },
    {
        id: "ACC-006",
        name: "Medias Crew Pack x3",
        category: "Accesorios",
        quality: "STANDARD",
        description: "Pack de 3 pares, algodón reforzado, caña media.",
        basePrice: 8000,
        image: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 6500,
        sizes: "35-45",
        colors: 6
    },
    {
        id: "ACC-007",
        name: "Riñonera Nylon Deportiva",
        category: "Accesorios",
        quality: "STANDARD",
        description: "Nylon resistente, cierre YKK, correa ajustable.",
        basePrice: 11000,
        image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 1600,
        sizes: "Único",
        colors: 5
    },
    {
        id: "ACC-008",
        name: "Mochila Urban Básica",
        category: "Accesorios",
        quality: "BASIC",
        description: "Mochila de poliéster con compartimento para laptop.",
        basePrice: 18000,
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
        stockStatus: "HIGH",
        totalStock: 900,
        sizes: "Único",
        colors: 4
    },
];