import type { Product } from '@/types/product';

export type { Product };

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "REM-001",
        name: "Remera Jersey 24/1 Peinado",
        category: "Remeras",
        quality: "BASIC",
        description: "Algodón 100% 24/1 peinado. Tapa costura en cuello y hombros. Ideal para serigrafía y DTF.",
        basePrice: 8500,
        stockStatus: "HIGH",
        totalStock: 3400,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: 15,
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80"
    },
    {
        id: "REM-002",
        name: "Remera Heavyweight Oversize",
        category: "Remeras",
        quality: "PREMIUM",
        description: "Algodón pesado 20/1. Calce boxy fit. Cuello de ripa de 3cm. Alta densidad premium.",
        basePrice: 14200,
        stockStatus: "HIGH",
        totalStock: 1200,
        sizes: ["S", "M", "L", "XL"],
        colors: 8,
        image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&q=80"
    },
    {
        id: "REM-003",
        name: "Musculosa Básica Rib",
        category: "Remeras",
        quality: "STANDARD",
        description: "Tejido rib 2x1 con spandex. Gran elasticidad y recuperación. Ideal para marca de autor.",
        basePrice: 7800,
        stockStatus: "LOW",
        totalStock: 85,
        sizes: ["XS", "S", "M", "L"],
        colors: 5,
        image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=500&q=80"
    },
    {
        id: "REM-005",
        name: "Chomba Pique Classic",
        category: "Remeras",
        quality: "STANDARD",
        description: "Tejido Piqué 30/1. Cuello y puños tejidos. Doble costura reforzada en laterales.",
        basePrice: 12900,
        stockStatus: "HIGH",
        totalStock: 2100,
        sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
        colors: 10,
        image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500&q=80"
    },
    {
        id: "REM-007",
        name: "Remera Escote V Basic",
        category: "Remeras",
        quality: "BASIC",
        description: "Jersey liviano 30/1. Cuello en V con terminación fina. Ideal para promociones.",
        basePrice: 8100,
        stockStatus: "HIGH",
        totalStock: 4500,
        sizes: ["S", "M", "L", "XL"],
        colors: 12,
        image: "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=500&q=80"
    },
    {
        id: "REM-008",
        name: "Remera Térmica Deportiva",
        category: "Remeras",
        quality: "NUEVO",
        description: "Poliester con elastano. Secado rápido. Costuras flatlock anti-roce.",
        basePrice: 11500,
        stockStatus: "HIGH",
        totalStock: 800,
        sizes: ["S", "M", "L", "XL"],
        colors: 3,
        image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=500&q=80"
    },
    {
        id: "REM-009",
        name: "Remera Boxy Acid Wash",
        category: "Remeras",
        quality: "NUEVO",
        description: "Jersey pesado con proceso de lavado ácido. Estética vintage lista para estampar.",
        basePrice: 16800,
        stockStatus: "LOW",
        totalStock: 120,
        sizes: ["S", "M", "L", "XL"],
        colors: 4,
        image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&q=80"
    },
    {
        id: "REM-011",
        name: "Remera Polo Jersey 24/1",
        category: "Remeras",
        quality: "STANDARD",
        description: "Algodón 24/1 peinado con cuello polo de la misma tela. Tapeta de dos botones reforzada.",
        basePrice: 11500,
        stockStatus: 'HIGH',
        totalStock: 1250,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: 8,
        image: "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=500&q=80"
    },
    {
        id: "REM-013",
        name: "Remera Manga Larga Rib 2x1",
        category: "Remeras",
        quality: "BASIC",
        description: "Tejido elástico de alta recuperación. Terminación en Overlock reforzada.",
        basePrice: 11200,
        stockStatus: 'LOW',
        totalStock: 45,
        sizes: ["XS", "S", "M", "L"],
        colors: 6,
        image: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=500&q=80"
    },
    {
        id: "REM-014",
        name: "Remera Crop Top Básica",
        category: "Remeras",
        quality: "STANDARD",
        description: "Corte por encima de la cintura. Jersey 30/1 liviano. Ideal para indumentaria femenina.",
        basePrice: 8900,
        stockStatus: 'HIGH',
        totalStock: 2100,
        sizes: ["S", "M", "L"],
        colors: 12,
        image: "https://images.unsplash.com/photo-1618517351616-38fb9c5210c6?w=500&q=80"
    },
    {
        id: "REM-015",
        name: "Remera Rugby Heavy Jersey",
        category: "Remeras",
        quality: "PREMIUM",
        description: "Jersey de 300 gramos. Cuello de gabardina blanca. Calce clásico de alta gama.",
        basePrice: 22000,
        stockStatus: 'OUT_OF_STOCK',
        totalStock: 0,
        sizes: ["M", "L", "XL", "XXL"],
        colors: 3,
        image: "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=500&q=80"
    },
    {
        id: "BUZ-001",
        name: "Buzo Canguro Frisa Invisible",
        category: "Buzos",
        quality: "PREMIUM",
        description: "Frisa pesada invisible (70/30). Capucha forrada y cordones de algodón.",
        basePrice: 28500,
        stockStatus: "HIGH",
        totalStock: 1800,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: 12,
        image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&q=80"
    },
    {
        id: "BUZ-002",
        name: "Buzo Cuello Redondo Basic",
        category: "Buzos",
        quality: "BASIC",
        description: "Frisa estándar 24/1. Calce regular. Ideal para bordados corporativos.",
        basePrice: 21000,
        stockStatus: "HIGH",
        totalStock: 2500,
        sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
        colors: 15,
        image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=500&q=80"
    },
    {
        id: "BUZ-004",
        name: "Buzo Medio Cierre Fleece",
        category: "Buzos",
        quality: "STANDARD",
        description: "Microfleece antipilling. Cierre YKK de 15cm. Excelente aislante térmico.",
        basePrice: 26000,
        stockStatus: "HIGH",
        totalStock: 900,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: 5,
        image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&q=80"
    },
    {
        id: "BUZ-005",
        name: "Buzo Crop Frisa Mujer",
        category: "Buzos",
        quality: "NUEVO",
        description: "Corte corto por encima de la cintura. Frisa soft con terminación de rib ancho.",
        basePrice: 23500,
        stockStatus: "HIGH",
        totalStock: 1100,
        sizes: ["XS", "S", "M", "L"],
        colors: 8,
        image: "https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=500&q=80"
    },
    {
        id: "BUZ-006",
        name: "Hoodie con Cierre Entero",
        category: "Buzos",
        quality: "STANDARD",
        description: "Cierre metálico reforzado. Bolsillos laterales. Frisa invisible premium.",
        basePrice: 31000,
        stockStatus: "HIGH",
        totalStock: 750,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: 4,
        image: "https://images.unsplash.com/photo-1542327897-d73f4005b533?w=500&q=80"
    },
    {
        id: "BUZ-007",
        name: "Buzo Oversize Rustico",
        category: "Buzos",
        quality: "NUEVO",
        description: "Rústico de algodón sin frisar. Ideal para media estación y layering moderno.",
        basePrice: 25800,
        stockStatus: "OUT_OF_STOCK",
        totalStock: 0,
        sizes: ["S", "M", "L", "XL"],
        colors: 5,
        image: "https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=500&q=80"
    },
    {
        id: "BUZ-008",
        name: "Cardigan de Lana Basic",
        category: "Buzos",
        quality: "STANDARD",
        description: "Tejido de punto acrílico alta calidad. Botones al tono. Ideal para uniformes.",
        basePrice: 29900,
        stockStatus: "LOW",
        totalStock: 30,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: 3,
        image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&q=80"
    },
    {
        id: "PAN-002",
        name: "Pantalón Cargo de Trabajo",
        category: "Pantalones",
        quality: "BASIC",
        description: "Gabardina de 8oz reforzada. 6 bolsillos funcionales. Triple costura.",
        basePrice: 27800,
        stockStatus: "HIGH",
        totalStock: 1500,
        sizes: ["38", "40", "42", "44", "46", "48", "50", "52"],
        colors: 4,
        image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500&q=80"
    },
    {
        id: "PAN-004",
        name: "Short de Baño Liso",
        category: "Pantalones",
        quality: "BASIC",
        description: "Microfibra plana secado rápido. Suspensor de red interno. Cordón de ajuste.",
        basePrice: 13500,
        stockStatus: "HIGH",
        totalStock: 3200,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: 15,
        image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500&q=80"
    },
    {
        id: "PAN-005",
        name: "Jogger Oversize Rústico",
        category: "Pantalones",
        quality: "NUEVO",
        description: "Calce ancho. Algodón rústico pesado. Sin puños en los tobillos para caída fluida.",
        basePrice: 24900,
        stockStatus: "LOW",
        totalStock: 65,
        sizes: ["S", "M", "L", "XL"],
        colors: 5,
        image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&q=80"
    },
    {
        id: "CAM-005",
        name: "Parka Gabardina con Corderito",
        category: "Camperas",
        quality: "PREMIUM",
        description: "Gabardina esmerilada pesada. Interior forrado en corderito sintético.",
        basePrice: 65000,
        stockStatus: "HIGH",
        totalStock: 400,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: 3,
        image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=500&q=80"
    },
    {
        id: "CAM-008",
        name: "Campera Rompeviento Forrada",
        category: "Camperas",
        quality: "STANDARD",
        description: "Exterior de sire repelente al agua. Forrería de red respirable.",
        basePrice: 36800,
        stockStatus: 'HIGH',
        totalStock: 920,
        sizes: ["S", "M", "L", "XL"],
        colors: 6,
        image: "https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=500&q=80"
    },
];