server {
    listen 80;
    server_name localhost;

    # Carpeta raíz desde donde se servirán los archivos estáticos
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Tipos MIME para compresión y correcto manejo
    include /etc/nginx/mime.types;

    # Esta es la parte más importante para Single Page Applications (React / React Router)
    # Si la ruta que busca el usuario no es un archivo ni un directorio válido, enviarlo a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuración de caché opcional (Recomendado para estáticos de React)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Evitamos que soliciten archivos ocultos (.git, .env, etc)
    location ~ /\. {
        deny all;
    }
}
